baseURL = 'http:/tayler.diesbackwards.com'
#baseURL='http://localhost'
languageCode = 'en'
defaultContentLanguage = "en"
title = 'Tayler Parsons'
description = "Software engineering & video game development blog alongside portfolio and project showcase"
theme = 'gokarna'
enableRobotsTXT = true
enableResourceImage = true
enableResourceLinks = true
enableEmoji = true

ignoreLogs = ['warning-goldmark-raw-html']

[params]
  footer = "Tayler Parsons"
  favicon = 'static/images/logo.ico'

  description = "Horse walks into a bar, barman asks \"why the long face?\""
  metaKeywords = ["blog", "golang", "unity", "unity engine", "game development", "tutorials", "video games"]
  site_type = "Person"

[params.assets]
  css = ["assets/theme_override.css"]
  js = ["assets/backgroundEffect.js"]

[menu]
  [[menu.main]]
    name = ""
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    url = "/posts/"
    name = "Blog"
    weight = 2

  [[menu.main]]
    identifier = "projects"
    url = "/projects/"
    name = "Projects"
    weight=3

  [[menu.main]]
    identifier = "tutorials"
    url = "/tutorials/"
    name = "Tutorials"
    weight=4

  [[menu.main]]
    identifier = "resume"
    url = "/pdfs/resume.pdf"
    name = "Resume"
    weight = 5

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 6

  [[menu.main]]
    identifier = "mail"
    url = "mailto:upsilon@diesbackwards.com"
    pre = "<span data-feather='mail'></span>"
    title = "Contact me!"
    weight = 7

  [[menu.main]]
    identifier = "linkedin"
    url = "https://www.linkedin.com/in/tayler-parsons/"
    weight = 8
    pre = "<span data-feather='linkedin'></span>"
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/UpsilonDiesBackwards"
    weight = 9
    pre = "<span data-feather='github'></span>"

  
  [[menu.main]]
    identifier = "youtube"
    url = "https://www.youtube.com/channel/UClO0xdAs0Z5K9ejHhV9_S-Q"
    weight = 10
    pre = "<span data-feather='youtube'></span>"
    
  [[menu.main]]
    identifier = "twitch"
    url = "https://www.twitch.tv/upsilondiesbackwards"
    weight = 11
    pre = "<span data-feather='twitch'></span>"


[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false